import { Metadata } from "next";
import { DocumentsContent } from "@/features/documents/DocumentsContent";

export const metadata: Metadata = {
  title: "Documents & Templates | HACKVERSE '26 | CodeBreakers GCEK",
  description:
    "Official HackVerse '26 documents, ideation PPT template, presentation decks, and institutional authorization NOC letter format.",
  keywords: [
    "hackathon documents",
    "HACKVERSE PPT template",
    "hackathon ideation template",
    "hackathon presentation deck",
    "institutional authorization letter",
    "NOC format hackathon",
    "college permission letter format",
    "hackathon submission template",
    "hackathon slides download",
    "ideation pitch deck format",
    "GCEK hackathon documents",
    "student NOC letter format",
    "head of institute permission letter",
    "hackathon document download",
    "PPT format for hackathon",
    "hackathon presentation PPT",
    "hackathon round 1 template",
    "hackathon round 2 template",
    "hackathon final pitch template",
    "authorization letter head of institute",
    "college approval form hackathon",
    "CodeBreakers official templates",
    "Hackverse downloadable documents",
    "student ID proof document format",
    "hackathon project report format",
    "hackathon architecture diagram template",
    "sample NOC letter Odisha colleges",
    "BPUT hackathon permission form",
    "engineering college NOC letter",
    "hackathon submission guidelines PDF",
    "hackathon brochure PDF download",
    "HACKVERSE rulebook PDF",
    "hackathon event schedule PDF",
    "hackathon problem statements PDF",
    "team registration confirmation doc",
    "evaluation scoring sheet PDF",
    "code of conduct declaration format",
    "hackathon mentor feedback form",
    "pitch deck guidelines 2026",
    "5 slide deck template hackathon",
    "problem solution architecture deck",
    "demo video submission guide",
    "GitHub repo documentation template",
    "README template for hackathons",
    "software license template open source",
    "hardware requisition form GCEK",
    "accommodation undertaking form GCEK",
    "travel allowance claim format",
    "participation certificate format",
    "winner certificate verification document",
  ],
  alternates: {
    canonical: "https://hackverse.codebreakersgcek.tech/documents",
  },
  openGraph: {
    title: "Documents & Templates // HACKVERSE '26",
    description:
      "Official HackVerse '26 documents, ideation PPT template, presentation decks, and institutional authorization NOC letter format.",
    url: "https://hackverse.codebreakersgcek.tech/documents",
    images: [{ url: "/og-image.png", width: 1200, height: 630, type: "image/png", alt: "HACKVERSE '26 Documents" }],
  },
  twitter: {
    card: "summary_large_image",
    title: "Documents & Templates // HACKVERSE '26",
    description: "Download official PPT templates, presentation decks, and sample NOC docs for HACKVERSE '26.",
    images: ["/og-image.png"],
  },
};

export default function DocumentsPage() {
  return <DocumentsContent />;
}
